import test from "node:test";
import assert from "node:assert/strict";
import { generateOutfitFlow, generateOutfits, missingCategoriesForAnchor } from "./outfitEngine.js";

const prefs={style:"Minimal",goal:"Работа",limits:[]};
const items=[
  {id:1,name:"Белая рубашка",type:"Верх",color:"Белый",style:"Minimal"},
  {id:2,name:"Чёрные брюки",type:"Низ",color:"Чёрный",style:"Minimal"},
  {id:3,name:"Синие джинсы",type:"Низ",color:"Синий",style:"Casual"},
  {id:4,name:"Белые кеды",type:"Обувь",color:"Белый",style:"Casual"},
  {id:5,name:"Чёрные лоферы",type:"Обувь",color:"Чёрный",style:"Minimal"},
];
test("anchor remains in every alternative",()=>{const looks=generateOutfits(items,prefs,[],1);assert.ok(looks.length>1);assert.ok(looks.every(x=>x.items.some(i=>i.id===1)));assert.ok(new Set(looks.map(x=>x.signature)).size>1)});
test("incomplete anchor outfit has no variants",()=>assert.deepEqual(generateOutfits(items.slice(0,2),prefs,[],1),[]));
test("missing categories are specific to anchor",()=>{assert.deepEqual(missingCategoriesForAnchor(items[0],items.slice(0,2)),["обувь"]);assert.deepEqual(missingCategoriesForAnchor({id:9,name:"Платье",type:"Платье"},[]),["обувь"])});
test("ordinary flow is generated by the candidate engine without public scores",()=>{
  const result=generateOutfitFlow(items,prefs);
  assert.ok(result.looks.length>1);
  assert.deepEqual(result.noCandidateReasons,[]);
  assert.ok(result.looks.every(look=>!("score" in look)&&!("scoreBreakdown" in look)&&!("rankingLevel" in look)));
});
test("anchor flow keeps the immutable anchor in every returned look",()=>{
  const result=generateOutfitFlow(items,prefs,[],2);
  assert.ok(result.looks.length>0);
  assert.ok(result.looks.every(look=>look.items.some(item=>item.id===2)));
});
test("flow exposes stable, understandable no-candidate reasons",()=>{
  assert.deepEqual(generateOutfitFlow(items.slice(0,2),prefs,[],1),{looks:[],noCandidateReasons:["missing_shoes"]});
  assert.deepEqual(generateOutfitFlow(items,prefs,[],999),{looks:[],noCandidateReasons:["anchor_not_found"]});
});
test("recent looks are deprioritized without weakening hard constraints",()=>{
  const first=generateOutfitFlow(items,prefs,[],1).looks;
  const next=generateOutfitFlow(items,prefs,[{signature:first[0].signature}],1).looks;
  assert.notEqual(next[0].signature,first[0].signature);
  assert.ok(next.every(look=>look.items.some(item=>item.id===1)));
});
